### ISSUE TITLE
[epic] New GIFT Data Portal working

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-portal#1]
Make a working data portal running off metadata and data stored in github.com/gift-data/ and following this mockup ... 

## Acceptance

Fully working app ready to demo to client with all main datasets in

* [x] Basic theme done similar to mockup – **DONE**: Looks very similar. See #9 and #10 for GIF/screenshot.
* [x] Home page similar to mockup – **DONE**: Looks very good. See #10.
* [x] Dataset page similar to mockup – **DONE**: Datasets content integrated, looks as expected. See #9.
* [x] Content page e.g. about page – **DONE**: There is an about page generated from Markdown. See #4.
* [x] Loads data from [gift-data repos](https://github.com/gift-data) – **DONE**: Data loads from gift-data repos, is parsed and cached. See #8.
  * [x] Can easily add new repos
  * [x] "Auto-rebuild" when these get updated (or way to trigger this for main site ...)

## Tasks

* [x] Get started: raw app working **DONE**: We have a basic app 
* [x] Basic tests: Set up very simple tests in cypress (2-4h) – **DONE**: Basic tests exist. See #2.
* [x] (Nice to have) Set up automated build on github pages with SSR (this should be possible as everything rendered at build time?) (2h) – **DONE**: The portal can be seen at https://gift-portal.vercel.app/ See #3.
* [x] Add an about page (2-4h) – **DONE**: Pages are generated from Markdown. See #4.
* [x] Dataset page fully working (~16h) – **DONE**: All sections of the page display as expected while the data comes from our DB. See #9.
  * [x] Get resource urls working in appropriate way
* [x] Home page dataset section (~16h) – **DONE**: The data shown in the datasets section of the home page is extracted from our DB. See #10.
  * [x] Render datasets – See #10.
  * [x] Search based on e.g. https://fusejs.io/ – See #11.
* [x] Move to live data load from github (8h) – **DONE**: Data loads from gift-data repos, is parsed and cached. See #8.
* Make the portal prettier:
    * [x] First pass on prettiness (without much design of content as data model not finished) (8h?) – **DONE**: Each section (nav bar, header, footer, etc.) exists as a component and is rendered individually. See #5.
    * [ ] Second pass on prettiness. – See #16. (Mostly done: needs some minor adjustments which aren't critical right now.)
* Demo to client:
  * [x] **16 December, 2020:** Showing the main features of http://gift-portal-git-master.datopian1.vercel.app/ in a state where it displays datasets that are not from GIFT (loaded locally, not from GitHub repos), with no search, random tags and metadata partially retrieved.
  * [x] **20 January, 2021:** Showing the "create flow", dashboard, login/logout feature and discuss next steps ("edit flow", documentation, missing features).
  * [ ] **17 February, 2021.**

# Analysis

## Principles

* Next.js app ... (don't worry about portal.js for now - we will refactor into that later)
* The data to power the app will if possible be local or done at build time ...

```
catalog = [
  'https://github.com/gift-data/presupuesto-mexico-2008-2019',
  'https://github.com/gift-data/republica-dominicana-gastos-economica-2014-2020',
  'https://github.com/gift-data/croatia-budget-spending'
]
```

At build time we will "import" these an**TBC** ind compile them ...

* We will retrieve datapackage.json
* We will retrieve README.md
  * We will add README as attribute
* (?) We will convert resource paths into "urls" (see below for algorithm)

```json=
var compiled_catalog = [
  {
    title: ...
    resources: [
      {
        path: ...
      }
    ]
  }
]
```

What "data" does each page need?

* Front page: whole catalog
* Dataset page `/dataset/presupuesto-mexico-2008-2019` will look up relevant 

## Info Architecture

```bash
/
/dataset/{xyz}
# not sure
/dataset/{xyz}/blob/{sha256}
/about
```

## Resource url compilation algorithm

There are 3 options for a resource path:

```json=
{
  // 1 path and relative file path and file is in git
  "path": "file1.csv"
  // 2 path and file in git lfs
  "path": file2.csv
  // 3 path is a url ..
  "path": "https://gob.mx/.../mydatafile.csv"
}
```

Process it to give me the actual url to this data:

* If already a url: DONE
* Go to github repo for this dataset
* Find the file
  * If in github return the "raw" url for github
  * If LFS file open lfsinfo and return me the computed path
    * Easy if we assume everything is public read (e.g. for OpenSpending).
    * If not may need giftless and authz involved (future)

**Comment by rufuspollock** [comment]
FIXED. It's pretty much done see https://gift-portal-git-master.datopian1.vercel.app/
