### ISSUE TITLE
Home page datasets section displays the correct data from sample datasets

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#10]
When I visit the home page, I want to see data coming from real datasets being extracted and displayed appropriately in the datasets section so I can know that the rendering of the data is working as expected.

## Acceptance

* [x] The data shown in the datasets section of the home page is extracted from our DB. __Done__ 

<img width="1371" alt="Screen Shot 2020-12-10 at 8 22 46 PM" src="https://user-images.githubusercontent.com/29900845/101819641-d3e8a500-3b25-11eb-9c71-74d1f7a7a98f.png">

## Tasks

* [x] Card layout – **DONE**: We use the same layout as agreed upon with GIFT and shown in the [mock-ups](https://www.figma.com/file/E6WVVyZynQtGPMHEu1q5d6/Portal).
* [x] Fill in with data from our db.

**Comment by sglavoie** [comment]
@risenW, correct me if I'm wrong, but this issue is technically done only in the branch `add-data`, right? I believe we will be able to mark this as done once that branch has been merged. I'm leaving it as is to be reviewed/closed in our sync tomorrow. :+1:

**Comment by risenW** [comment]
@sglavoie yes it is. Once we push the final change master later today, I'll update with the link.

**Comment by risenW** [comment]
@sglavoie This issue can be closed now
