### ISSUE TITLE
Download files not working

### ISSUE THREAD

**Issue by cotts** [datopian/gift-portal#104]
When I want to see the dataset details, I want to be able to download the resources in the download session

## Acceptance Criteria
- [x] Download resources if the repository is public 

## Tasks
- [x] Update download resource link
- [x] check if resource is public
- [x] download public resource is working
