### ISSUE TITLE
[checklist] Display accurately the creation and modification dates (main page and dataset page)

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#105]
## Acceptance

* [x] Datasets should display accurately the creation and modification dates (e.g. `Created: 5 months ago`) and update the `Updated:` metadata as necessary. **Done** See screenshots below

<img width="1063" alt="Screen Shot 2021-02-16 at 10 11 07 AM" src="https://user-images.githubusercontent.com/29900845/108041954-81ed5f80-703f-11eb-994d-f62c5328e1d6.png">
<img width="1039" alt="Screen Shot 2021-02-16 at 10 11 48 AM" src="https://user-images.githubusercontent.com/29900845/108041961-84e85000-703f-11eb-9b06-88ba33ee0412.png">

## Tasks

* [x] Make sure the creation date corresponds to the date when the dataset is being added on GitHub (should already be the case).
* [x] Make sure the update date corresponds to the last date at which the dataset was modified (whenever a save is changed when editing a dataset).
* [x] Use an easy-to-read and convenient format (see **Analysis below**) by using something like `moment.js`.

## Analysis

* For simplicity's sake, we could indicate the dates by relying on [moment.js](https://stackoverflow.com/a/39309538/8787680) instead of having to take into account all possible edge cases manually. It could then display results in a format such as:
  * `Created: 2 years and 3 months ago` when the dataset is older than 1 year and a month.
  * `Created: 1 year ago` when the dataset is older than 1 year but still less than a year and a month (so we don't display `1 year and 0 month ago`).
  * `Created: 3 months ago` when the dataset is older than a month (or `1 month ago` if it's been a month).
  * `Created: 14 days ago` when the dataset is less than a month old.
* Should take into account the plural form (i.e. show `1 month` and not `1 months` for days, months and years).
* When applicable, we should have `X year and Y month`, `X month and Y day` and `X day` alone when `X > 0`and `Y > 0`, also taking into account the plural form when `X > 1` or `Y > 1`, accordingly.
