### ISSUE TITLE
[checklist] Search in the portal should behave as expected and include correct results that can be sorted alphabetically

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#107]
## Acceptance

* [x] Search should be possible when typing `Enter` as well as when clicking on the magnifying glass icon next to the search input field.
* [x] Search should match only relevant datasets.
* [x] An empty search should return all datasets (or just don't search at all) OR there should be a way to clear the search to make the datasets appear again.
* [x] Sorting of datasets should work (since there are no options to sort other than "alphabetically", it should just sort based on the title of the datasets).
* [x] When showing a subset of the existing datasets, e.g. by searching for `mexico`, the total number of datasets should be displayed, not the number of results.
* [ ] When the search matches no dataset, the text `No results found for this search query.` is displayed in the main section of the page as shown below.

![image](https://user-images.githubusercontent.com/32682903/107803615-72f96b00-6d28-11eb-981e-aecfc7f18bae.png)

## Tasks

* [x] Update fuse.js sorting function - **DONE** : 20fac66dceca90bfb7a11f07abb5d3e20e794e2d
* [x] Activate the sorting input filed to control how fuse.js sort dataset **DONE**: 20fac66dceca90bfb7a11f07abb5d3e20e794e2d
* [x] Add keyevent to input search field to enable search on `Enter` key - **DONE**: 84c6a7b93aa3508f601e1cf0312464b02d2dfc74
* [x] Update `handleSearch` to return all dataset on empty string - **DONE** 20fac66dceca90bfb7a11f07abb5d3e20e794e2d

## Analysis

* Search should match only relevant datasets:
  * E.g. when searching for `croatian`, only the dataset `Croatian Budget and Spending` should be returned. Currently, there are other matches that do not contain the word `croatian` anywhere. This would be similar to searching for a repo at https://github.com/gift-data where partial matches return relevant datasets only and include results matching the description (e.g. https://github.com/gift-data?q=keyword). (Note: I assume searching within tags would also work)
* When showing a subset of the existing datasets, e.g. by searching for `mexico`, the total number of datasets should be displayed, not the number of results:
  * I.e. the text should be, in this example, `Showing 1 of 15 datasets`, not `Showing 1 of 1 datasets`.

**Comment by risenW** [comment]
@steveoni Can you add an image or video showing this fix as well

**Comment by sglavoie** [comment]
Thank you @risenW for pointing that out! :slightly_smiling_face: 

@steveoni, I've updated the acceptance criteria to include an omission dealing with the absence of results. Thank you. :wink:
