### ISSUE TITLE
Dataset search should be integrated with fusejs.io

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#11]
When I search for datasets, I want the results to be returned correctly based on the matched keywords I input so I can quickly and reliably find the datasets I am looking for.

## Acceptance

* [x] Searching for datasets works and returns the appropriate results based on keywords, including those from a title, description and/or a tag. __Done__

![Screen Recording 2020-12-10 at 8 20 16 PM](https://user-images.githubusercontent.com/29900845/101822140-2d9e9e80-3b29-11eb-913b-49d8e36804c3.gif)

# Tasks

* [x] Use fusejs.io
* [x] Install fuse.js
* [x] convert dataset to a format compatible with fuse.js
* [x] add search event to search component
* [x] Use react hook (useState) to track changes in dataset from fuse.js

**Comment by rufuspollock** [comment]
@sglavoie @steveoni can you finish the analysis here e.g. list of tasks.

**Comment by risenW** [comment]
@sglavoie This is good to close as well
