### ISSUE TITLE
File preview (and file content) shows wrong file encoding

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#118]
When I work with existing OpenSpending datasets, I want to obtain them in the standard UTF-8 encoding so I can load them in the Portal and download them without facing file encoding issues.

## Acceptance

* [x] All existing resources from all datasets in https://github.com/gift-data/ use the standard UTF-8 file encoding and display as expected (contain no weird escape sequences).

## Tasks

* [x] Update the Python script we have to save all files in their raw form (bytes). – **DONE: Files are saved as a stream of bytes.**
* [x] Test the encoding of a few different resources (e.g. from Paraguay, Costa Rica and Uruguay) and confirm it looks good. **DONE: The character set used is the expected one as seen in https://github.com/gift-data/presupuesto-de-uruguay https://github.com/gift-data/paraguay-2017 https://github.com/gift-data/costa-rica-presupuesto-ingresos-2020**
* [x] Re-download all resources for GIFT datasets, update repos with Git-LFS and local Giftless server. **DONE: All repos updated as can be seen for now here with 12 Feb as the latest update: https://github.com/gift-data/**
* [x] Re-generate `sample` property in all `datapackage.json` files. **DONE: All files updated, see all relevant repos at https://github.com/gift-data/**

## Analysis

* Using the `requests` library in Python, the encoding is not always detected accurately so using the `.text` attribute instead of `.content` leads to unexpected results in a couple of datasets. The `.content` attribute contains the content of the file in bytes which avoids this pitfall when saving that stream to disk.

**Comment by sglavoie** [comment]
FIXED: All tasks done. All repos in https://github.com/gift-data/ use UTF-8 file encoding. Can be seen in places such as:

* https://github.com/gift-data/croatia-budget-spending/blob/main/datapackage.json#L1210
* https://github.com/gift-data/republica-dominicana-gastos-economica-2014-2020/blob/main/datapackage.json#L955
* https://github.com/gift-data/presupuesto-mexico-2008-2019/blob/main/datapackage.json#L6028
* https://github.com/gift-data/presupuesto-de-uruguay/blob/main/datapackage.json#L3019
