### ISSUE TITLE
Datasets sorting should work when displaying results from a search as well as on its own without searching first

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#129]
* When I use the **Sort by** feature, I want to sort datasets in the expected order (both ascending and descending) so I can find the datasets I am looking for more easily.

## Acceptance

* [x] The user can sort datasets alphabetically based on the `title` property of a dataset in ascending (A to Z) and descending order (Z to A).
* [x] The user can update the order of the sort after a search was made by selecting a different sort option (`A to Z` if `Z to A` was selected and vice versa). In other words, the user can change the sorting order without having to do another search. **DONE** - https://github.com/datopian/gift-portal/blob/41bed79f74d9c111aa08a7f6830e6585fc915e4c/pages/index.js#L44

## Tasks

* [x] Trigger sorting event function whenever a sort option is selected **DONE** - https://github.com/datopian/gift-portal/blob/41bed79f74d9c111aa08a7f6830e6585fc915e4c/pages/index.js#L44
* [x] Update the dataset state with the sorted data **DONE** - https://github.com/datopian/gift-portal/blob/41bed79f74d9c111aa08a7f6830e6585fc915e4c/pages/index.js#L44

## Analysis

* Sorting is currently not happening.

**Comment by steveoni** [comment]
@sglavoie this is implemented in #107 .  But the way it is implemented is that users click how to sort the dataset, before typing the keyword to search for.

The implementation can be changed though.

**Comment by sglavoie** [comment]
Thank you for your comment @steveoni. I am not still clear how the sorting is happening, but maybe we can review this once #130 is done so that we look at the sorting based on the title of the dataset instead of the name of the repository. :slightly_smiling_face: 

Here are a few screenshots where we might expect a different order (maybe?). I select Ascending/Descending before starting the search and typing `Enter`.

![image](https://user-images.githubusercontent.com/32682903/108144859-18e20800-7090-11eb-87c5-6991739d87f4.png)
![image](https://user-images.githubusercontent.com/32682903/108144887-25666080-7090-11eb-823f-917ab566c347.png)
![image](https://user-images.githubusercontent.com/32682903/108144956-4333c580-7090-11eb-8152-904593f38f8d.png)

**Comment by steveoni** [comment]
okay @sglavoie let's wait till when the title name is fixed and then review it togther

**Comment by sglavoie** [comment]
@steveoni sure! In fact, Rising already updated the property to use `title` instead of `name` (it's been integrated in the portal):

![image](https://user-images.githubusercontent.com/32682903/108276357-4e90fa80-713d-11eb-9a9b-22922bdc7366.png)

**Comment by steveoni** [comment]
@sglavoie so is it working now?

**Comment by sglavoie** [comment]
@steveoni Yes, it looks good! I added an acceptance criterion to clarify what's needed. So right now:

* :heavy_check_mark: We can pick whether we sort `A to Z` or `Z to A` **before** doing a search.
* :x: Next step would be to allow users to change the sorting order **after** a search was made.
  * So if the user searched for something and the sort was `A to Z`, they should be able to display the same results with `Z to A` without having to restart the search... and the same would be through from `Z to A` to `A to Z`.

**Comment by sglavoie** [comment]
FIXED: The work was finished in #140.
