### ISSUE TITLE
Update Token Settings

### ISSUE THREAD

**Issue by cotts** [datopian/gift-portal#138]
When I will manage a resource through a giftless server, I want to pass the right permissions for each resource in use, so I need to generate a token configuration and send it as a Header.

## Acceptance Criteria
- [ ] Token must have the right object
- [ ] All routes that access `giftless-server` must have the token set

## Tasks
- [ ] Refactor permissions scopes
- [ ] Update Token object
- [ ] Update routes that access `giftless-server` using token

## Analysis

After the requirement to block anonymous usage of giftless-server on [Gift-Publisher Issue](https://github.com/datopian/gift-publisher/issues/45), the `gift-portal` authorize methods must be updated based on the 
 [giftless documentation](https://github.com/datopian/giftless/blob/6d7fb5e37f62b18e94f2afe992100c3acfbec0ab/docs/source/auth-providers.md)
