### ISSUE TITLE
Make the portal a lot prettier – Second pass on prettiness

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#16]
When I visit the _[final version of the] (?)_ GIFT portal, I want to see a visually appealing design with nice touch ups applied on top of the first iteration (see #5) so I can find all the information I need in a neatly organized website that looks modern, is readable and easy to use.

## Acceptance

* [x] The portal is accessible both on mobile and desktop devices (focuses is on desktop) and displays nicely (improved fonts, spacing, styling fixing issues shown in the screenshots under the **Analysis** section below).

## Tasks

This is all self-explanatory where the status of a task was not detailed further: see https://gift-portal-git-master.datopian1.vercel.app/

* [x] Change fonts.
* [x] Make the portal responsive.
  * [x] Add `@media-queries` (not necessarily mobile first as the publisher will be used on desktop anyways).
  * [x] Test on iPhone 6/7/8, Samsung Galaxy S5, iPad.
  * [x] Test the height of elements (cards showing datasets).
  * [x] Check that the text `Sort by:` is responsive and shown at the correct size (probably should appear at `sm`all size).
* [x] Fix footer section.
  * [x] Align icons.
  * [x] Remove border.
  * [x] Update text color from white to light gray.
  * [x] Make the icons in footer clickable.
* [x] Fix navbar section.
  * [x] Remove visual glitches around logo.
  * [x] Export logo as PNG.
  * [x] Add text decoration (underline) to links.
  * [x] Add missing orange borders (left of logo and right side of page).
  * [x] Add links to elements in menu.
  * [x] Resize the icons.
  * [x] Add slight drop-shadow to elements, including SVG icons.
  * [x] Add missing hover effects in menu.
  * [x] Fix the "About us" icon being truncated at the bottom.
  * [x] Make the logo and title "Data Portal" clickable.
* [x] Improve design of main page.
  * [x] Fix spacing issues (see screenshot: height of input box, space between datasets, etc.).
  * [x] Reduce spacing around tags.
* [x] Improve design of dataset page.
  * [x] Style elements in dataset page.
    * [x] Style download section. **DONE: Converted to a responsive table instead of `div` tags.**
    * [x] Style file preview.
  * [x] Fix spacing issues (description, tags, title size, etc.).
  * [x] Align elements properly in the Metadata section.
  * [x] Make the "share" icon clickable.
  * [x] Fix the maximum size issue with icons in the **Metadata** section.
  * [x] Style list items in **Metadata** section.
  * [x] Metadata section has been re-styled to accommodate new fields (e.g. Disaggregation, Budget stage) and typos were fixed (e.g. `Disaggregation`, not `Disagregation`).
* [x] Add favicon.
* [x] Links have been styled with transitions.
* [x] Fix typos and punctuation issues **in the Portal** (mostly missing period).
* [x] Fix typos and punctuation issues **in the Publisher** (mostly missing period).
* [x] Metadata screen has been re-styled to accommodate new fields (e.g. Disaggregation, Budget stage) and typos were fixed (e.g. `Disaggregation`, not `Disagregation`).
* [x] Dashboard page has been re-styled coherently with the rest of the design.
* [x] Elements in the Publisher flow have been re-aligned and spaced out to occupy more width on the screen.

### Main page

* The portal is currently not responsive at all:

![image](https://user-images.githubusercontent.com/32682903/103694622-e2797f00-4f60-11eb-899b-9501a693bbae.png)
![image](https://user-images.githubusercontent.com/32682903/103694638-e9a08d00-4f60-11eb-98cb-440f2fa66b2a.png)
![image](https://user-images.githubusercontent.com/32682903/103694665-f45b2200-4f60-11eb-9a6c-2cbab056939d.png)

* Spacing is off pretty much everywhere (need to check on mobile too):

![image](https://user-images.githubusercontent.com/32682903/103695093-94b14680-4f61-11eb-8c37-4b5778513dff.png)

* Fix footer section (align icons, remove border, change fonts):

![image](https://user-images.githubusercontent.com/32682903/103695286-e8239480-4f61-11eb-966f-6bf3c636bdbf.png)

* Fix visual glitches around logo (missing orange border on the left side too):

![image](https://user-images.githubusercontent.com/32682903/103695429-2a4cd600-4f62-11eb-8265-e76204e9ff48.png)

* Fix links and hover effects in menu.

### Dataset page

* Improve spreading/spacing of metadata:

![image](https://user-images.githubusercontent.com/32682903/103695565-713acb80-4f62-11eb-8ed4-ea605c9a0e29.png)

* Style download section.
* Style file preview.

* Improve spacing at the top (description, tags, title size, etc.):

![image](https://user-images.githubusercontent.com/32682903/103695656-9f201000-4f62-11eb-87e6-301cac05b78b.png)

* Make it responsive

![image](https://user-images.githubusercontent.com/32682903/104641330-3d9d2700-566f-11eb-98e3-86012dcea4d8.png)

* Issue with icon size in **Metadata** section

![image](https://user-images.githubusercontent.com/32682903/109191488-d7222300-775b-11eb-9fe2-e103d77f2ce2.png)

* To style React components, this reference might be useful: https://create-react-app.dev/docs/adding-a-stylesheet/
* ~~We first need to agree on what "a lot prettier" means so we do not waste anyone's time working on tasks that won't be brought up to fruition.~~

**Comment by sglavoie** [comment]
FIXED: The portal and publisher have been restyled based on the mock-ups.

![2021-03-03_12-15](https://user-images.githubusercontent.com/32682903/109852521-78a4eb00-7c1a-11eb-9d44-a3d99fe5b0cb.png)
![localhost_3000_ (1)](https://user-images.githubusercontent.com/32682903/109852522-793d8180-7c1a-11eb-95e3-e8bbe5e2032b.png)
![localhost_3000_ (2)](https://user-images.githubusercontent.com/32682903/109852524-793d8180-7c1a-11eb-957d-53734a23a2d9.png)
![localhost_3000_ (3)](https://user-images.githubusercontent.com/32682903/109852526-79d61800-7c1a-11eb-8357-969caffaebf9.png)
![localhost_3000_ (4)](https://user-images.githubusercontent.com/32682903/109852527-79d61800-7c1a-11eb-9f46-2430b8059ac2.png)
![localhost_3000_ (5)](https://user-images.githubusercontent.com/32682903/109852529-7a6eae80-7c1a-11eb-8200-44559ea61fdf.png)
![localhost_3000_admin_publisher_costa-rica-presupuesto-ingresos-2020](https://user-images.githubusercontent.com/32682903/109852530-7a6eae80-7c1a-11eb-8013-3831f45326f1.png)
![localhost_3000_admin_publisher_edit-metadata_presupuesto-de-uruguay](https://user-images.githubusercontent.com/32682903/109852532-7a6eae80-7c1a-11eb-99d8-e059008f3a8c.png)
![localhost_3000_admin_publisher_presupuesto-de-uruguay](https://user-images.githubusercontent.com/32682903/109852534-7b074500-7c1a-11eb-9895-b4e0b9e29bd3.png)
![localhost_3000_dashboard](https://user-images.githubusercontent.com/32682903/109852537-7b9fdb80-7c1a-11eb-99d8-187c7a54fa54.png)
