### ISSUE TITLE
`datapackage.json` should contain only one `schema` property and keep track of `sample` appropriately

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#162]
* When I add my first resource to a newly created dataset, I want to show a `sample` property containing maximum 30 rows at the top-level in the generated `datapackage.json` and a `sample` property inside each resource also containing maximum 30 rows so I can keep the file short and sweet.
* When I add my first resource to a newly created dataset, I want to show a `schema` property at the top-level of `datapackage.json` and no `schema` property inside each individual resource.\*

\* This is so because the `schema` has to be the same for each resource, otherwise the resource can't be added to the dataset.

## Acceptance

* [ ] There is a single `schema` property at the top-level of the `datapackage.json` for a given dataset, even when it contains multiple resources.
* [ ] There is a `sample` property at the top-level of the `datapackage.json` for a given dataset (if necessary\*) containing maximum 30 rows and there's a `sample` property inside each resource containing a `sample` property also with a maximum of 30 rows.
* [ ] When a resource is deleted, the `sample` property at the top-level should match that of one of the remaining `sample` property/properties from another resource (i.e., the `sample` property at the top-level of `datapackage.json` cannot be empty as in `sample: []` unless there is no resource in the dataset).\*

\* Note: I think we could go without using a `sample` at the top-level and just use the `sample` from the first resource because it should always match anyways, but feel free to make the minimum amount of changes to make this work (we can keep the `sample` at the top-level as long as **its content is not empty when at least one resource still exists** AND as long as **it matches the `sample` of a resource that hasn't been deleted from the dataset**).

## Tasks

* [ ] Ensure that only one `schema` property exists at the top-level of `datapackage.json` after uploading more than one resource to a new dataset.
* [ ] Ensure that a `sample` property exists for each resource AND that it's maximum 30 rows.
* [ ] Ensure that the top-level `sample` property matches that of an existing resource in the dataset when deleting a resource (i.e. it's only ever `sample: []` when there are no resources in a dataset, otherwise it should be equal to the sample of another resource still in the dataset).

## Analysis

If you look at this file, I've added 3 resources to a newly created repo: https://raw.githubusercontent.com/gift-data/test-crud-dataset-3/045d831c17d1d63250586c9cb04d3febd7f84631/datapackage.json

1. The `sample` property is fine at the top-level (30 rows displayed) but contains too many rows inside the resources. For instance, the first resource in that file is `data/simple_heavy3.csv` and it has 384 rows.
2. Are we using the sample inside each resource somewhere? It looks to me like one sample at the top-level should be enough to give a sense of what the dataset contains, but we can leave it there as that might be useful in the datapackage.json itself (but we should definitely make sure they are shorten down to 30 rows or so!).
3. I wonder why we have a `schema` property inside each resource as well as at the top-level. The schema is shown for the first resource and then is empty for the subsequent resources being added to the dataset (I mean, the `schema` property inside subsequent resources is empty). Shouldn't we discard the `schema` property inside all resources and just keep it at the top-level?

**Comment by risenW** [comment]
@sglavoie 

>  There is a single schema property at the top-level of the datapackage.json for a given dataset, even when it contains multiple resources.

A resource by frictionless specification should have a schema property, as regards the schema at the top level, we currently set/get it from the schema of the first resource in a data package, and as such, it takes care of when resources are deleted, as the schema can be easily updated. sEE https://github.com/gift-data/epo-datapackage/blob/2a1838271d7b83ce3a8958490bcd84ac1e8778a7/datapackage.json#L5612

> There is a sample property at the top-level of the datapackage.json for a given dataset (if necessary*) containing maximum 30 rows and there's a sample property inside each resource containing a sample property also with a maximum of 30 rows.

This is already in place. As soon as you add a resource, a sample is added to the resource and also the top level package. See https://github.com/gift-data/epo-datapackage/blob/2a1838271d7b83ce3a8958490bcd84ac1e8778a7/datapackage.json#L6 and https://github.com/gift-data/epo-datapackage/blob/2a1838271d7b83ce3a8958490bcd84ac1e8778a7/datapackage.json#L2787

> When a resource is deleted, the sample property at the top-level should match that of one of the remaining sample property/properties from another resource (i.e., the sample property at the top-level of datapackage.json cannot be empty as in sample: [] unless there is no resource in the dataset).*

Already in place. We are currently doing this.

**Comment by sglavoie** [comment]
@risenW

> as regards the schema at the top level, we currently set/get it from the schema of the first resource in a data package

OK, I understand that it makes sense to have a schema for each resource to comply with the standard. However, if you look at this commit https://github.com/gift-data/test-crud-dataset-3/commit/5cc7ac64eeb3227d1792c5556b06eb7e27dc8df6, you can see that before deleting the resource from the dataset, the schema inside the resource was empty, which shouldn't be expected, right?

> a sample is added to the resource and also the top level package.

I see this is the case when you create a new dataset, but this is not so when removing a resource. If you look at this same commit, https://github.com/gift-data/test-crud-dataset-3/commit/5cc7ac64eeb3227d1792c5556b06eb7e27dc8df6, you can see that the resource (which was removed in that commit) had a `sample` property but there is no `sample` at the top-level. Also, I chose this commit because the `sample` inside the resource contains 460 rows and makes for a very convoluted `datapackage.json`. We should limit the size of the sample to 30 rows for both the top-level `sample` property as well as for the `sample` for each resource.

On deleting a resource:

> Already in place. We are currently doing this.

I chose this commit because it also shows this behavior: https://github.com/gift-data/test-crud-dataset-3/commit/5cc7ac64eeb3227d1792c5556b06eb7e27dc8df6

A resource was previously deleted and the `sample` at the top-level is empty despite the fact there is still one resource in the dataset. Looking back a few commits when there were 3 resources, this makes it clear that we went from 3 resources down to 2 and that the `sample` was left empty: https://github.com/gift-data/test-crud-dataset-3/commit/14a3f5e784673d9ca768dbcb940cdaab22130cd5

In this later commit, you can also see that the `sample` at the top-level contains 30 rows while the `sample` for the resource being deleted contained 460 rows.

I hope that helps clarify a bit. Please let me know otherwise and I will find more examples. :+1:

**Comment by risenW** [comment]
@sglavoie Going through your examples, I see that the problem is we're trying to manage sample and schema in two different places. In the data package and in resources. I'm proposing making this simpler by always getting sample/schema from the first resource in a data package. That way even if the first resource changes,  it will always refer to the first resource. 

So basically I'm saying, we get rid of the top level schema and sample properties and always get it from the first resource if available. Does this make sense to you?

**Comment by sglavoie** [comment]
@risenW That makes perfect sense! So to recap: all resources would have a `schema` and a `sample` but those properties will no longer exist at the top-level. I wasn't sure if we were using them from the top-level somewhere but in this case, I agree it will be easier to manage and cleaner to just have that info inside the resources.

I will update the description of the issue to reflect this change. Thank you. :slightly_smiling_face: :+1:

**Comment by risenW** [comment]
@sglavoie Great, once you're done updating the issue. I'll work on it Monday morning.

**Comment by risenW** [comment]
@sglavoie I'm transferring this issue to gift-publisher as this fix was performed there.
