### ISSUE TITLE
Display dataset image in the home and dataset page

### ISSUE THREAD

**Issue by risenW** [datopian/gift-portal#165]
When I visit GIFT portal, I want to be able to visually identify datasets by looking at an icon/logo being uploaded for each dataset both in the home page and in the page of a given dataset so I easily recognized the owner of a dataset at a glance.

## Acceptance

* [x] There is an icon/logo for datasets showing up in the top-left corner of a **dataset card in the home page** (to the left of the title of the dataset). **Done** See #166 and images below
* [x] There is an icon/logo for datasets showing up in the top-left corner of the **dataset page** (to the left of the title of the dataset). **Done** See #166 and images below
* [x] When a dataset doesn't have an icon or logo (no URL set for the `image` property), no icon is shown but the same space is occupied (as if the icon was invisible). [Applies to both the home page and dataset page so that titles are aligned] **Done** See #166 and images below

<img width="1363" alt="Screen Shot 2021-03-19 at 12 00 58 PM" src="https://user-images.githubusercontent.com/29900845/111771362-e05e6580-88ab-11eb-9026-58f606b6d720.png">
<img width="890" alt="Screen Shot 2021-03-19 at 12 02 18 PM" src="https://user-images.githubusercontent.com/29900845/111771373-e48a8300-88ab-11eb-8092-14b4abfd9b9c.png">
