### ISSUE TITLE
Load `gift-os-types` from the `gift-data` organization

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#178]
## Acceptance

* [x] Repo https://github.com/datopian/gift-os-types has been copied to https://github.com/gift-data/gift-os-types and the portal/publisher loads the OpenSpending types from there. **Done** https://github.com/gift-data/gift-os-types
* [x] https://github.com/gift-data/gift-os-types is neither accessible from the portal nor from the dashboard. **Done** See #182 

## Tasks

* [x] Copy https://github.com/datopian/gift-os-types to https://github.com/gift-data/gift-os-types.
* [x] Update code so that we fetch GitHub repos from https://github.com/gift-data and exclude `gift-os-types` (won't be displayed in the portal or in the dashboard).

## Analysis

* We need to copy https://github.com/datopian/gift-os-types so that it's loaded from https://github.com/gift-data.
* This way, GIFT can manage it fully from the `gift-data` organization.
