### ISSUE TITLE
Refactor db getCatalog etc into a MetaStore class

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-portal#18]
We want to abstract the backend so that we can refactor it as needed going forward without changing "frontend" code.

## Acceptance

* [x] Clean MetaStore class abstracting catalog with clear init methods called on boot **DONE** Metastore created in https://github.com/datopian/gift-portal/blob/feature/metastore/lib/metastore.js

## Tasks

* [x] Create tests **DONE** test created in c6562bb643c11cb3a5971375282b7a25113418f6 . Blocker: mocha can't be used to test utils functions since creating a babel config file will conflict with nextjs root configuration
* [x] Create `MetaStore` class **DONE** https://github.com/datopian/gift-portal/blob/feature/metastore/lib/metastore.js 
* [x] refactor getCatalog to `initMetaStore` (make sure we have a basic test ...) **DONE** https://github.com/datopian/gift-portal/blob/feature/metastore/lib/metastore.js
* [x] add getDataset method **DONE** https://github.com/datopian/gift-portal/blob/feature/metastore/lib/metastore.js
* [x] add getCatalog method (trivial) **DONE** https://github.com/datopian/gift-portal/blob/feature/metastore/lib/metastore.js

```
class MetaStore() // abstraction of Dataset catalog
  _catalog: {
    ...
  }

  async getDataset(id):
    dataset = _catalog[id]
    dataset = tidyDataset(dataset)
    return dataset
  
  async initMetaStore(listOfDatasets)
      // load from github
      // store into 
      
      
  async initMetaStoreFromLocalDisk(directories)
   
  // getResource(datasetId, resourceId)
```

**Comment by sglavoie** [comment]
FIXED: All initial tasks were completed.
