### ISSUE TITLE
All GIFT datasets should be uploaded to the portal with validated rich types

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#184]
## Acceptance

* [x] All GIFT datasets have been uploaded to the portal with validated rich types

## Tasks

* [x] Upload all the data for the following datasets:
  * [x] costa-rica-presupuesto-egresos
  * [x] costa-rica-presupuesto-ingresos
  * [x] croatia-budget-spending
  * [x] estimates-of-national-expenditure-2021-22
  * [x] mexico – **DONE: Depended on the resolution of https://github.com/datopian/gift-publisher/issues/88**
  * [x] paraguay
  * [x] presupuesto-uy-desde-2011
  * [x] republica-dominicana-gastos-economica-2014-2020
  * [x] south-africa-national-estimates-2015-2019
  * [x] south-africa-provincial-estimates-2018-2019

**Comment by sglavoie** [comment]
Depends on the resolution of datopian/gift-publisher#88

**Comment by sglavoie** [comment]
FIXED: All datasets were uploaded to https://gift-portal.vercel.app/dataset/mexico

![screencapture-gift-portal-vercel-app-dataset-mexico-2021-08-20-08_20_05](https://user-images.githubusercontent.com/32682903/130239456-afa34d03-8313-40a5-b6f6-05fdb7e2f9f8.png)
