### ISSUE TITLE
Authentication (Login) via Github

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-portal#19]
Users should be able to log into gift-portal using GitHub authentication to enable downloading and editing of dataset resources.

## Acceptance

* [x] `/login` url exists and takes me to a page where it says "Login via GitHub" or similar **DONE**:https://github.com/datopian/gift-portal/blob/b1b2eecf744b92ee22a4b92f4177709db9911749/pages/login.js
* [x] On clicking login via github you are dispatched off to github ... and return with you logged in **DONE** https://github.com/datopian/gift-portal/blob/b1b2eecf744b92ee22a4b92f4177709db9911749/pages/login.js
* [x] Cookie etc setup and your username/gravatar picture shown **DONE**: make use of `useSession` provided by `next-auth.js`

## Task

* [x] configure `next-auth.js` authentication api. - **DONE**: https://github.com/datopian/gift-portal/blob/b1b2eecf744b92ee22a4b92f4177709db9911749/pages/api/auth/%5B...nextauth%5D.js
* [x] create a custom `/login` page **DONE**: https://github.com/datopian/gift-portal/blob/b1b2eecf744b92ee22a4b92f4177709db9911749/pages/login.js
* [x] include `next-auth.js` context api to make session accessible across all page. **DONE**: https://github.com/datopian/gift-portal/blob/b1b2eecf744b92ee22a4b92f4177709db9911749/pages/_app.js

## Analysis

Base on research, authentication in nextjs is made easier by using `next-auth.js` which provide easy access to manage all type of authentication `github, twitter, email e.t.c` .

It also gives the ability to share session across all pages by following the following steps;
1.  Specify the provider to use, since we are using github, we specify github provider
      ```js
       import NextAuth from 'next-auth';
       import Providers from 'next-auth/providers';

       const options = {
          providers: [
             Providers.GitHub({
                  clientId: process.env.GITHUB_CLIENT_ID,
                  clientSecret: process.env.GITHUB_CLIENT_SECRET
             })
         ]
       }

      export default function Api(req, res) {
           return NextAuth(req, res, options);
       }
      ```
2.  `next-auth.js` also has a react hook function to automatically handle `sessions` with `Login` and `Logout`
      ```js
      import  { signIn, signOut, useSession } from 'next-auth/client';
      ```

Every page can always query `useSession` hook to see if a user is login and also obtain login user email, username and gravatar

**Comment by rufuspollock** [comment]
Great work @steveoni

One small thing:

* Can we style the login page so it looks ok (not much needed here but some small tweaks would be nice e.g. centred button, some instructions etc - see datahub.io/login for example)
* Authorize application page on github currently asks me to give permission to all my organizations. This is not needed i think - all we need is personal profile info for the gravatar.
* Can we show that you are logged in somewhere e.g. profile picture in navbar and logout option (cf datahub.io again).
