### ISSUE TITLE
Basic tests: Set up very simple tests in cypress

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#2]
* Part of Epic #1 

When an existing page of the portal is modified, I want to be able to rely on a test suite that can be run to alert me in case I end up breaking the code when working on the portal so I can keep on top of things and fix issues as soon as they are being noticed, maintaining a high development speed while avoiding slowdowns due to preventable errors that can be tested for.

## Acceptance

* [x] Having breaking changes that affect the main pages (home and dataset details page) lead to the test suite flagging issues so we always maintain a clean `master` branch passing against tests. – **DONE**: Tests fill fail and the commit will not be pushed. (https://github.com/datopian/gift-portal/actions)
* [x] The test suite is run automatically every time a commit is pushed to the repository. – **DONE**: See tests running https://github.com/datopian/gift-portal/runs/1511177951?check_suite_focus=true.
* [x] We have documentation in the README explaining how to run the test suite locally. – **DONE**: See https://github.com/datopian/gift-portal/blob/master/README.md.

## Tasks

* [x] Install cypress – **DONE**.
* [x] Test for front page – **DONE**: Tested in commit f285e5678101a4313eb6f3a2202601b0f7736f9f. Checking for icons and text.
* [x] Test for one dataset page – **DONE**: Tested in commit f285e5678101a4313eb6f3a2202601b0f7736f9f. Checking for presence of text.
* [x] Set up github actions so these run on every push – **DONE**: Set up in commit 371daba0bfd45019e599a21b81ee2216e1a716ec. Build on push.
* [x] Add instructions to README for running locally. – **DONE**: Instructions added in commit e07e8185bd7b37b6b33115dfcfb4c10099f0f8a1.

**Comment by rufuspollock** [comment]
@steveoni re-opening this issue for minor item that we should have a "test/build status" badge of some kind at the top of our README

(i assume you know the kind of thing e.g. on https://github.com/datopian/datapub)

![image](https://user-images.githubusercontent.com/180658/102867305-dd80df80-4438-11eb-989d-a8c73c987735.png)

**Comment by steveoni** [comment]
ok. I will do that

**Comment by steveoni** [comment]
done
