### ISSUE TITLE
Metadata download on dataset page

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-portal#20]
I want to be able to download the full metadata (datapackage.json) so that i have it locally and can use it to get data

## Acceptance

* [ ] `/dataset/{id}/files/datapackage.json` url exists and returns the `datapackage.json`
* [ ] Link to that url in dataset (showcase) page
* [ ] The metadata (datapackage.json) should include a `download_url` to right location on portal website

## Tasks

TODO

**Comment by sglavoie** [comment]
We may still want to support this in the future (issue categorized as **Someday Maybe**), so leaving a short comment about it.

Possible workarounds:

* **[No further work required]** The person publishing a dataset can edit the metadata for a given dataset and click on "Download Package" to get the `datapackage.json`.
* **[Small change required]** For the public at large, a link could be shown to download `datapackage.json` (as the first row in the table showing resources available to download) straight from the GitHub repository on each dataset by using the dataset title to set the correct URL.
