### ISSUE TITLE
Portal not loading: showing the message "This Serverless Function has timed out" (error 504)

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#202]
Context:

* All resources for this dataset were re-uploaded one after the other: https://github.com/gift-data/south-africa-national-estimates-2015-2019
* After the last resource was added, the following error appeared:

![image](https://user-images.githubusercontent.com/32682903/136034666-8153f926-63f5-42f1-80ca-2f4b75d96d6f.png)

## Acceptance

* [ ] The portal can be loaded without error.
* [ ] We understand the error and know how to prevent it in the future.
* [ ] The fix for this 504 error has been applied.

## Tasks

* [ ] Read the logs to understand what happened.
* [ ] Bring the appropriate fix (TBC).

## Analysis

* Vercel logs will be available at https://gift-portal.vercel.app/_logs
* Note: it's not the first time this error occurred. We may find more info in the logs if we have a lot of them.
* Vercel link saying how to fix the error: https://vercel.com/docs/error/application/FUNCTION_INVOCATION_TIMEOUT

/cc @nirabpudasaini @SusanBot85
