### ISSUE TITLE
Resolve Inconsistent Error 

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-portal#207]
We want to ensure the site stop having downtime 

## Acceptance

- [x] Ensure cause of downtime are identified
- [x] Prevent Down time

## Task

- [x] update Graphql Query to fetch only datapackage.json from repo and not all files in the repo
- [x] update util functionality responsible for fetching datapackage.json

## Analaysis

From vercel investigation, the site can be down for two main reason (base on current investigation)

1) Based on payload time: if the user uploads large files against the normal repo structure, the graphql will try to load such resources which might exceed vercel payload time. This will result to this error: `[ERROR] [1648467449652] LAMBDA_RUNTIME Failed to post handler success response. Http response code: 413.`

2) The other error needs further investigation on how to resolve it:

```
eca566c	ERROR	ApolloError: Response not successful: Received status code 502
    at new ApolloError (/var/task/node_modules/@apollo/client/errors/errors.cjs.js:31:28)
    at /var/task/node_modules/@apollo/client/core/core.cjs.js:1490:19
    at /var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:958:69
    at new Promise (<anonymous>)
    at Object.error (/var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:958:21)
    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:140:18)
    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.error (/var/task/node_modules/zen-observable/lib/Observable.js:240:7)
    at /var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:946:68
    at Array.forEach (<anonymous>) {
  graphQLErrors: [],
  networkError: Error [ServerError]: Response not successful: Received status code 502
      at Object.throwServerError (/var/task/node_modules/@apollo/client/link/utils/utils.cjs.js:45:17)
      at /var/task/node_modules/@apollo/client/link/http/http.cjs.js:32:19
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    response: Response {
      size: 0,
      timeout: 0,
      [Symbol(Body internals)]: [Object],
      [Symbol(Response internals)]: [Object]
    },
    statusCode: 502,
    result: { data: null, errors: [Array] }
  },
  extraInfo: undefined
}
2022-03-26T13:27:01.011Z	8cb75c3c-cde2-466b-9667-1e0caeca566c	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Response not successful: Received status code 502","reason":{"errorType":"Error","errorMessage":"Response not successful: Received status code 502","graphQLErrors":[],"networkError":{"errorType":"ServerError","errorMessage":"Response not successful: Received status code 502","name":"ServerError","response":{"size":0,"timeout":0},"statusCode":502,"result":{"data":null,"errors":[{"message":"Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `A0BE:786E:7D47E:17C6B5:623F14A3` when reporting this issue."}]},"stack":["ServerError: Response not successful: Received status code 502","    at Object.throwServerError (/var/task/node_modules/@apollo/client/link/utils/utils.cjs.js:45:17)","    at /var/task/node_modules/@apollo/client/link/http/http.cjs.js:32:19","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]},"message":"Response not successful: Received status code 502","stack":["Error: Response not successful: Received status code 502","    at new ApolloError (/var/task/node_modules/@apollo/client/errors/errors.cjs.js:31:28)","    at /var/task/node_modules/@apollo/client/core/core.cjs.js:1490:19","    at /var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:958:69","    at new Promise (<anonymous>)","    at Object.error (/var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:958:21)","    at notifySubscription (/var/task/node_modules/zen-observable/lib/Observable.js:140:18)","    at onNotify (/var/task/node_modules/zen-observable/lib/Observable.js:179:3)","    at SubscriptionObserver.error (/var/task/node_modules/zen-observable/lib/Observable.js:240:7)","    at /var/task/node_modules/@apollo/client/utilities/utilities.cjs.js:946:68","    at Array.forEach (<anonymous>)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Response not successful: Received status code 502","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:326:22)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
Unknown application error occurred
```
This error resulted from graphql API call to Github API. Based on a quick look it seems to be fetching a lot of resources on a single API call.

similar errors
https://github.community/t/something-went-wrong-while-executing-your-query-c7d21412cc35c4e105a/13732/2
https://github.community/t/something-went-wrong-while-executing-your-query-c7d21412cc35c4e105a/13732/5

**Codebase study**

After looking at the github API query here https://github.com/datopian/gift-portal/blob/master/lib/queries.js , we are calling all the files in all repo, when our main focus should be the `datapackage.json`, hence the query will be refactor to

```js
query { 
  viewer {
      organization(login: "gift-data") {
        repositories(
          first: 100
          affiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]
          ownerAffiliations: [OWNER, COLLABORATOR, ORGANIZATION_MEMBER]
        ) {
          totalCount
          pageInfo {
            endCursor
            hasNextPage
          }
          nodes {
            name
            description
            url
            createdAt
            updatedAt
            resourcePath
            viewerPermission
            id
            owner {
              login
            }
            object(expression: "main:datapackage.json") {
                    ... on Blob {
                      oid
                      text
                      byteSize
                    }
            }
          }
        }
      }
    }
}
```
Tested with https://docs.github.com/en/graphql/overview/explorer

with the query change, some part of the code will be refactored in `lib/utils.js`-> `processRepo` function
