### ISSUE TITLE
Authorization API with Scopes

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-portal#21]
Create an Authorization API to generate/verify tokens to manage datasets (access and save)

## Job Story

When I have a dataset I want only authorized users to be able to update it so that it is not messed with

When I have a datset I want to be able to limit access to view it to authorized users so that ...

Lower level:

When want to save my datasets, I need a authorization route to generate token to give me permissions to upload the files

When I want to access my dataset (and its resources) I want to have scopes granted ...

## Acceptance

* [ ] Function to load permissions matrix from github (with test) `loadPermissions(org, token) => { repoName: { read: [ array of user names ], 'write': ...` (see below in analysis) token should be a token of a user with admin rights on org so they can look up permissions)
* [ ] `authorize(user, scopes)` function using those permissions (with test)
  ```
  authorize(user, scopes) =>
    {
      requested_scopes - list of permission scopes requested
      granted_scopes - list of permission scopes granted
    }
  ```
* [ ] POST API `/api/authorize?...` same as https://github.com/datopian/ckanext-authz-service#authorize
  * NB: the user you are seeking the authorize with this method is the "current user" (ie. who has logged in or PUBLIC if no-login).
  * For tests this can be set as part of the test (need to check how nextjs records current user`)
  * For manual testing we'd either need to be able to run app in test mode where this auto-set or wait until we  implement authentication ...

The only scopes we need to handle are of the form:

```
ds:{name-of-dataset}:read/write
```

Any other scope should result in a 400 error, bad request with response message:

`Invalid scope. Scope should be of form "ds:{name-of-dataset}:read/write/admin"`

Authorize API Response:

```
token - the encoded / signed / encrypted JWT token
user_id - the authorized user name
expires_at - token expiration time in ISO-8601 format
requested_scopes - list of permission scopes requested
granted_scopes - list of permission scopes granted
```

## Questions

To validate the authorization the permission I assume that the user must be logged in and I have a github token, right? 
 
 
## Tasks
 
* [x] Set Authorization Strategy
* [x] Load permissions info from github for a given org `getGithubPermissions(org)` - 1d **DONE. 1d. https://github.com/datopian/gift-portal/pull/24**
  * Note this may need for the app to have an api key / token that is authorized on github (probably admin on the org). This would be set in an environment variable. For trying out use "your own" token. For tests you should be mocking the github API anyway so this is not relevant.
  * Get the list of repos in the org
  * For each repo get the list of collaborators with their permissions e.g. https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#collaborators (may be graphql version)
    * Map push => read, pull => write, admin => admin
    * Consolidate all users in given category together into array so we have e.g. `read: [username, username2, ...]`
    * Add: "PUBLIC", "LOGGED_IN" to read list
* [ ] Implement `authorize` function - 1d
* [ ] Implement Authorization Route
  * [ ] Start with some tests
  * [ ] Generate scopes etc
  * [ ] Create token
    * i need the private key (in environment of the app)
    * An example of generating JWT tokens for Giftless in Python: https://github.com/datopian/ckanext-authz-service/blob/master/ckanext/authz_service/authzzie.py#L155
    * authorization: `path, sha256` https://github.com/datopian/giftless/blob/master/giftless/auth/jwt.py#L15
  * [ ] Overall response 

## Analysis
 
To implement this feature, will be used as example the [ckan-authz-service](https://github.com/datopian/ckanext-authz-service) that is a CKAN plugin that add to CKAN new API routes (authorize and verify token). 

This token generated in this API will be used on a giftless server to upload the datasets

## Approach

How does authorization work in giftless?

What is core function?

```
getScopes(dataset, user) => returns scopes
```

Principles

* People login in via github and we use their github username as their identifier
* We use permissions on github to manage access rather than inventing our own for now ...

`getScopes` Algorithm

* When the app loads we go to github org and we load a list of all the repos and create a map:
  ```
  {
    dataset (repoName): {
      editors: [user names]
      readers: [PUBLIC, LOGGED_IN, user names ...]
      admin: 
    }
  }
  ```
* Then `getScopes(dataset, user)`. NB: user can be PUBLIC or LOGGED_IN
  * Checks: is user in list of editors? if so add that scope
  * Checks: is user in list of readers? if so add relevant scope
