### ISSUE TITLE
Resource Downloading

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-portal#22]
When visiting a dataset (showcase) page I want to download the data so that I can use it

Currently link urls do not work (see problem section in analysis below)

## Acceptance

* [x] I can download resources in a dataset

In particular

* [x] New route exists `dataset/{id}/files/default/{sha256:sha256+size}` that redirects to file in storage
  * [x] 401 if insufficient permission
* [ ] BONUS: `dataset/{id}/files/default/{path}` works where path is path on resource in data package.

## Tasks

2 parts:

* [x] Create a download path - see section below - {0.5}
* [x] Showcase page: setup these links in showcase page (quite easy) - just `files/default/{resource path}` or can use sha256 and file size if exists  - {0.5}

### Create download path

* [x] Stub new route for `dataset/{id}/files/default/{resourceId}` where resourceID is like `sha256:{sha256}+{size}`  - {1}
* [x] Implement giftless-client-js (`batch` only)  **FIXED. https://github.com/datopian/giftless-client-js/issues/1** 
* [x] Get a token form authz (we may hardcode authz to allow read access)  - {0.5}
* [x] Use giftless client to get the url and redirect to that  - {0.5}

Algorithm for generating storage download url upon request to `dataset/{id}/files/default/{sha256:sha256+size}`:

* [x] Get the dataset metadata for dataset `{id}`
* [x] get the url of giftless server (may have this in dataset metadata)
* [x] get the file oid (sha256) + size (from dataset resource or simply from the url path!)
* [x] get an authz token to read the file for giftless via `Permissions.authorize`
* [x] go to giftless server with oid, size and token (and possibly a file name to use) and get a download url - use giftless-client-js
* [x] redirect to that URL

### Problem

How do we generate resource urls so that a user can download the file?

Imagine i have loaded my datapackage.json

https://github.com/gift-data/presupuesto-mexico-2008-2019/blob/master/datapackage.json#L709

```
"path": "data/presupuesto_mexico__2008.csv",
```

This exists in github but is a git-lfs pointer

```
version https://git-lfs.github.com/spec/v1
oid sha256:8dd79f5157b17024b83526a68bbe7180f1b5388aedebfc07e9b8d812b69fc07e
size 72590620
```

Somehow for this to render in the gift portal frontend we need to compute the actual storage url ...

At the moment we get a 404 e.g. on a link like https://gift-portal-git-master.datopian1.vercel.app/dataset/data/concat.csv on this page https://gift-portal-git-master.datopian1.vercel.app/dataset/AT33.Tirol%202007-2013%20ERDF

### Solution

Algorithm for generating storage url:

* lfsinfo: get the url of giftless
* get the file contents with oid (sha256) + size
* get an authz token to read the file for giftless
* go to giftless with oid, size and token
* get a url from giftless
* set that as `storage_url` on datapackage.json - use that url in UI

Another approach, create new route:

```
dataset/{id}/files/{sha256+size}
// in future may support path which involves lookup in datapackage.json
dataset/{id}/files/{path}
```

And this redirects to storage ...

**Comment by cotts** [comment]
@rufuspollock:  Related to 

> * [ ]  BONUS: `dataset/{id}/files/default/{path}` works where path is path on resource in data package.

 It will not work on the same route as the `dataset/{id}/files/default/{sha256:sha256+size}` in the case the path will have more than one level: e.g.: `data/file.csv`, and in this case must be another route or strategy.
