### ISSUE TITLE
Incremental Static generation 

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-portal#27]
The static page should always be automatically built at a given time interval to contain new information

## Acceptance

* [x] `index.js` and `[datasetId].js` should contain command to always rebuild the pages at the time requested

## Task

* [x] remove the former method of loading data from github and saving in a json file
* [x] update the `getStaticProps` in `index.js` and `[datasetId].js` to always fetch from github and build the page automatically at a given time

## Analysis

@rufuspollock I want to bring to your notice a specific feature in Next.js;

But before I do, here is the approach we are currently using in the gift-portal app; In the `getStaticProp` we fetch data from github and the data is then stored in a json file in `/db/data.json`. This `data.json` is used to generate the static page for Home page and also for the dataset dynamic routing.

One disadvantage of this approach is that the `data.json` must always be pushed to github in order to build the static page and there is no way to update the app without pushing the data since it's needed whenever the static page is being generated.

To solve this, I think we can use **Incremental static regeneration** provided my nextjs which give us the ability of normal server rendering with static page generation https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration .

With this we can build the static page directly with data fetch from github without saving it in a json file, this data is cached in building the static page hence it doesn't fetch from github whenever users visit the site. And also we can always add the time interval to which the static page is regenerated, hence if there are new data in the gift portal, it will be included in the new build.

Hence we might not even need a MetaStore #18 to store data and be passed around.

**Comment by steveoni** [comment]
@rufuspollock I want to bring to your notice a specific feature in Next.js;

But before I do, here is the approach we are currently using in the gift-portal app; In the `getStaticProp` we fetch data from github and the data is then stored in a json file in `/db/data.json`. This `data.json` is used to generate the static page for Home page and also for the dataset dynamic routing.

One disadvantage of this approach is that the `data.json` must always be pushed to github in order to build the static page and there is no way to update the app without pushing the data since it's needed whenever the static page is being generated.

To solve this, I think we can use **Incremental static regeneration** provided my nextjs which give us the ability of normal server rendering with static page generation https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration .

With this we can build the static page directly with data fetch from github without saving it in a json file, this data is cached in building the static page hence it doesn't fetch from github whenever users visit the site. And also we can always add the time interval to which the static page is regenerated, hence if there are new data in the gift portal, it will be included in the new build.

Hence we might not even need a MetaStore #18 to store data and be passed around.

cc:/ @risenW
