### ISSUE TITLE
[Nice to have] Set up automated build on github pages with SSR

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#3]
* Part of Epic #1 

When I commit changes to the repo, I want an automated build to be done (with SSR) and show the results with GitHub Pages so I can quickly keep my teammates in the loop and have an easy way to ensure that the code hosted on GitHub will render properly once used in production.

## Acceptance

* [x] An automated build process is set up on GitHub.  – **DONE**: The magic happens here https://github.com/datopian/gift-portal/blob/master/.github/workflows/main.yml
* [x] ~~GitHub Pages~~ Vercel is used to display the rendered version of the portal. – **DONE**: The portal can be seen at https://gift-portal.vercel.app/ and the Vercel bot on GitHub confirms a successful deployment after the merge of #17 in this comment https://github.com/datopian/gift-portal/commit/a0ac1f310618d19adf2208a9e26568377995b4a3#commitcomment-45108958

## Tasks

* [x] Set up an automated build process on GitHub. – **DONE**: The magic happens here https://github.com/datopian/gift-portal/blob/master/.github/workflows/main.yml
* [x] ~~Set up GitHub Pages.~~ Render the website on Vercel (due to the need for SSR). – **DONE**: The portal can be seen at https://gift-portal.vercel.app/

**Comment by steveoni** [comment]
@sglavoie  I think this issue can now be closed base on #17

**Comment by sglavoie** [comment]
**FIXED**: The tasks were done (using Vercel instead of GitHub Pages due to the need for SSR). The portal can be seen at https://gift-portal.vercel.app/

Great work @steveoni! :tada: I've updated the description of the issue to reflect the current state of things. :wink:
