### ISSUE TITLE
Work out how we handle globals in NextJS that are loaded at build time

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-portal#31]
For MetaStore (#18, #8) and for Authorization (#21) we want to load the information once (at build time) from an external source (github) and then use that throughout the app. For example, for authorization:

* NextJS app is deployed
* Load Permissions from Github <- we want to do this once when the app is booted (NOT on every request)
* Save the permissions somehow so available to each request ...
* On a given request i want to call authorize(..) using those saved permissions

```javascript=
// Boot up code somewhere

globals.metastore = MetaStore()
metastore.fetchFromGithub(org=env.GITHUB_ORG)

github = Github(env.GITHUB_TOKEN, env.GITHUB_ORG)
const permissionsData = gitub.getPermissions()

// later in a route that does authorization...
import permissionsData from "globals/permissions.json"

def route(req, res):
  permissions = Permissions(permissionsData)
  permissions.authorize(...)
  ...
```

## Acceptane

* [ ] We have a pattern for doing this
* [ ] We use this pattern for e.g. authorize and metastore

## Tasks

* [x] research options **DONE. See analysis below.**
* [x] identify approach ** Ans: Build this info outside of nextjs at build time and save to a json file ... Here's how you add a script to nextjs build process: https://dev.to/nalanj/adding-scripts-to-next-js-n7i. See more in Solution section below.**
* [ ] trial and validate it e.g. for authorize
* [ ] SEPARATE: ~~implement for metastore (separate issue)~~

### Solution

Build this info outside of nextjs at build time and save to a json file ...

Here's how you add a script to nextjs build process: https://dev.to/nalanj/adding-scripts-to-next-js-n7i

Suggest

* one script per thing being loaded
* output resulting data to `db/{name}.json`

### Research

See this thread on this exact topic: https://github.com/vercel/next.js/discussions/15054

Running the scripts over an npm script will be a better solution that will not require extensive configuration and/or maintenance

* The scripts will be add on `./scripts` 
* All of them will run over an *npm script*, e.g.: `npm run database` 
* This script will be added to run together with the deploys `npm build: npm run database && next build`
* All information will be stored at `./data/*.json`
* If will require any other organization information, that can be passed as parameter. 
 

### FAQs

when the organization update some repository permission, what will happen with the permission already stored on nextjs app? won't it will be outdated and require a reboot to update? **Yes, it will be outdated and they need to rebuild/redeploy the app**

Options: 

Running as scripts, every time the app is booted or deployed will generate an updated database and also allows to update them through a route or a specific button (allowed only to admins)
