### ISSUE TITLE
Embed Publisher app (SPA) into Portal App (Next.JS)

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-portal#37]
We want to embed the publisher app within the gift portal at e.g. `/admin/publisher` so that we have a coherent experience and can make authenticated calls from SPA into APIs (to get authorization and save via dataset API).

## Acceptance

* [x] We have a recommended way to do this that allows embeds publisher app at a particular tag or commit **DONE**
* [x] We have tried it out **DONE**
* [x] We should have https://datopian.github.io/gift-publisher/ present in `/admin/publisher`  **DONE**- https://gift-portal-git-publisher.datopian1.vercel.app/admin/publisher
* [x] We have documentation in the README for how to update going forward

## Tasks

* [x] convert `gift-publisher` to react component library and push to npm **DONE**- https://www.npmjs.com/package/giftpub
* [x] create a `/admin/publisher` route for Publisher app as SPA **DONE**- https://gift-portal-git-publisher.datopian1.vercel.app/admin/publisher
* [x] Transfer the code from https://github.com/datopian/gift-publisher to `gift-portal` to be presented in `/admin/publisher` **DONE**

## Analysis

* [x] Understand the code structure at https://github.com/datopian/gift-publisher
* [x] check how to transfer the SPA to gift-portal nextjs app either to use (nextjs router or react router)

**Comment by sglavoie** [comment]
Note: we can strip out the SVG for now to make it work.
