### ISSUE TITLE
Add an about page

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#4]
* Part of Epic #1 

When I visit the rendered portal, I want to see an _About page_ that I can click on and visit so I can incorporate additional pages to the website that are needed by GIFT (the _About page_ being one such example not yet shown in the mockups at this stage).

## Acceptance

* [x] There is an _About page_ that can be visited that creates pages from markdown and frontmatter material in a folder. – **DONE**: Pages are generated from Markdown here https://github.com/datopian/gift-portal/blob/master/pages/about/%5Babout%5D.js

## Tasks

Stub an about page that creates pages from markdown and frontmatter material in a folder (can follow the next.js example https://github.com/vercel/next.js/tree/canary/examples/blog-starter)

* [x] Identify how to do this. – **DONE**.
* [x] Stub 2 pages of content – **DONE**: They are here https://github.com/datopian/gift-portal/tree/master/_about
* [x] Add a test to cypress (should fail) – **DONE**: We have tests here https://github.com/datopian/gift-portal/blob/master/cypress/integration/pages/about/about_spec.js
* [x] Add in router etc to make this render. – **DONE** They render at `/about/name_of_page`
