### ISSUE TITLE
Login Authentication before Accessing Gift-Publisher

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-portal#41]
I want only login user to access the `admin/publisher`

## Acceptance

* [ ] Login detail should be validated before accessing gift-publisher
* [ ] redirect to login page if not login
* [ ] redirect to dashboard page when log in

## Task

* [ ] create login validator in `admin/publisher`
* [ ] create dashboard page `admin/dashboard`
* [ ] create a redirect function to login and dashboard

**Comment by sglavoie** [comment]
FIXED: This was addressed in PR #158.
