### ISSUE TITLE
Dataset Metadata API

### ISSUE THREAD

**Issue by cotts** [datopian/gift-portal#46]
API to save dataset metadata (data package) to MetaStore (GitHub with datapackage.json)

When saving a dataset's metadata I want an API so that the publisher app can use that API to save to MetaStore

## Acceptance

* [x] `POST /api/dataset/{id}` exists and receives as payload a Frictionless data package and saves this to relevant repo on github
  * [x] Should check permissions (does the user making this request have permission for this repo)
  * [x] author in git should be user who makes request. Commit message can be gerneric
  * id should be the dataset name (i.e. the repo name) e.g. `/api/dataset/presepuesto-mexico`

TODO: do we distinguish create vs update? Opinions?
Using a PUT route to update the metadata information.

## Tasks

* [x] Stub API route
* [x] Add test for route with mocks (maybe configure metastore lib with filesystem backend for tests)
* [x] Check permissions (use the permissions data we retrieve at load time in class `Permissions`) - we can do that by checking if current user is in write or admin list of relevant repo
  * [x] Test for this ...
* [x] Use metastore-lib-js to issue create or update command to create stuff on github
  * [x] Get the giftless server url from the environment

```
 {
    "dataset": "recline",
    ...
    "editors": [
      "Liyubov",
      "mariorodeghiero",
      "shubham-mahajan"
    ],
    "admins": [
      "mariorodeghiero",
      "shubham-mahajan"
    ]
  },
```
