### ISSUE TITLE
Github User Token

### ISSUE THREAD

**Issue by cotts** [datopian/gift-portal#48]
When Manage data on `gift-portal` I want to manage the data based on logged user on Github

## Acceptance

- [x] Load data based on the logged user that will be used on #42, #46, and #22 
- [x] Get user token to use inside API and GitHub requests

## Tasks
- [x] Store user token on session
- [x] Update documentation
