### ISSUE TITLE
Add login/logout buttons with avatar to the portal redirecting to the appropriate routes

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#49]
* When I land on the gift-portal web application, I want to be able to click on a "Log in" button to authenticate myself so I can create/update datasets and be redirected to the dashboard page to allow me to do so.
* When I am logged in on the gift-portal web application, I want to be able to click on a "Log out" button and see my avatar near that button so I know I am correctly authenticated and have a way to log out to close a session, redirecting me to the main page of the web application (same page shown to first-time visitors).

## Acceptance

* [x] A login button is shown to the visitor who has yet to authenticate on the web application.
* [x] A logout button (with accompanying avatar showing which user is logged in) replaces the login button when the user is already logged in and allows to log out from a session.

<img width="1436" alt="Screen Shot 2021-01-19 at 11 14 17 AM" src="https://user-images.githubusercontent.com/29900845/105020426-9261e880-5a47-11eb-8289-afc81d18d506.png">

<img width="1440" alt="Screen Shot 2021-01-19 at 11 06 01 AM" src="https://user-images.githubusercontent.com/29900845/105020417-8ece6180-5a47-11eb-9e23-694f4f33ffe4.png">

## Tasks

* [x] Update the mock-ups to show how we want this information to be displayed. @sglavoie **In Progress: [Screenshot for desktop shown in this comment below](https://github.com/datopian/gift-portal/issues/49#issuecomment-762335019).**
* [x] Integrate the login/logout buttons and avatar in the portal.
  * [x] Make the login button appear when the user is not yet authenticated (text to show: `Log in`). Make logging in redirect to the dashboard page to take further actions.
  * [x] Make the logout button appear when the user is logged in with its accompanying avatar to be identified unambiguously (text to show: `Log out`). Make logging out redirect to the main page (same page shown to first-time visitors).

**Comment by sglavoie** [comment]
@risenW I will add the mock-ups for the mobile version later as I will need to make some other changes to accommodate this on all screen sizes but that is now good to go:

![image](https://user-images.githubusercontent.com/32682903/104936891-c0c1c400-5972-11eb-93a0-bdf06b6b8b6f.png)

**Note:** this colored square would be exactly half the width of the other ones but I can take care of the details for the CSS later as I will make more changes anyways. :+1: 

**Note 2:** I think the avatar will require a stroke around it (grey like the color in the footer and in the other icons in the navbar to guarantee there's going to be enough contrast with the background color) but I can see that with CSS later too :slightly_smiling_face:.
