### ISSUE TITLE
Make the portal a bit prettier - First pass on prettiness (without much design of content as data model not finished)

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#5]
* Part of Epic #1 

When I visit the portal, I want to see that we are on track to having a website that looks like the [Figma prototypes](https://www.figma.com/file/E6WVVyZynQtGPMHEu1q5d6/Portal) we have done in terms of the disposition of the elements on the page (layout) so I can confidently know we will be able to deliver a more polished version of it on time for our next meeting with GIFT (**TBC**: possibly on 16 December).

## Acceptance

* [x] The portal follows the layout defined in the Figma prototype and contains all the basic elements on the page (header, footer, navbar, placeholder for title, etc.) and the theme is rendered as expected. **DONE** : The header, footer, Navbar e.t.c are all implemented and can all be viewed in https://github.com/datopian/gift-portal/blob/master/pages/index.js and each component can be viewed individually in https://github.com/datopian/gift-portal/tree/master/components

## Tasks

* [x] Setup tailwind-**DONE**: https://github.com/datopian/gift-portal/blob/master/tailwind.config.js contains the basic configuration base on the mock-up design
* [x] Basic theme layout- **DONE**: Layout to be apply to all pages is created as a component https://github.com/datopian/gift-portal/blob/master/components/Layout.js and applied to all pages here: https://github.com/datopian/gift-portal/blob/master/pages/index.js
* [x] navbar- **DONE**: Navbar is created as a component https://github.com/datopian/gift-portal/blob/master/components/Navbar.js
* [x] Footer - **DONE**: also as a component https://github.com/datopian/gift-portal/blob/master/components/Footer.js
* [x] Placeholder for front page dataset content - **DONE**: also as a component https://github.com/datopian/gift-portal/blob/master/components/Card.js
* [x] Render title and not much else on dataset page - **DONE**: https://github.com/datopian/gift-portal/blob/master/pages/dataset/%5Bdatasetid%5D.js
* [x] Render content pages - **DONE** dataset content page https://github.com/datopian/gift-portal/blob/master/pages/dataset/%5Bdatasetid%5D.js
