### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by rufuspollock** [datopian/gift-portal#61]
## Acceptance

* [x] `/dashboard` page exists and works if i am logged in and shows what login shows atm when i login (o/w 404)
* [x] Next to each dataset is right text for link (link still goes to same place i.e. the publisher app with the right id)

## Tasks

* [x] Relocate this to /dashboard (and have login redirect here on successful login) (currently at /login) 
  * [x] Also logout action should redirect to home page
* [x] Next to each dataset **Done** See image below
  * [x] "Create a fiscal data schema" with link to publisher app `/admin/publisher/{id}` IF dataset descriptor (data package content) has NO resources
  * [x] "Edit fiscal data package" with link to `/admin/publisher/{id}` IF dataset has resources array with at least one entry
  * [ ] FUTURE: "Add data to fiscal data package"
* [x] List of datasets
  * [x] Remove description column **Done** See video below

<img width="1027" alt="Screen Shot 2021-01-26 at 2 06 32 PM" src="https://user-images.githubusercontent.com/29900845/105849540-d1141780-5fe0-11eb-9102-fe068f2e6d0e.png">

**Comment by risenW** [comment]
## Blocker acceptance criteria 2:

 When retrieving repos, we need to specify a branch so we can retrieve all repo + contents at once. The default branch for new repositories created on github is `main`, but older repositories still use `master`. If I specify branch to be `master`, the contents of a repo with branch `main` returns null. 

Possible solutions:
1. We can make two requests using both main and master branches, and merged the results.( A little bit hacky)
2. Get a list of all repo names in organisation and try getting their content (for both master and main) with individual request to github api

**Comment by sglavoie** [comment]
@risenW All the repos now have their default branch set to `main` :+1: (see #70 for details).

**Comment by risenW** [comment]
@cotts can you update the acceptance with screenshots or preferably videos
