### ISSUE TITLE
Check user permissions on API

### ISSUE THREAD

**Issue by cotts** [datopian/gift-portal#67]
When I access `gift-portal` API routes, I want to have the user information to check permissions.

## Acceptance Criteria

- [x] Have all API routes with the user logged information when accessed 
- [x] Check the user permissions inside all API routes
- [x] Validate response and methods allowed

## Tasks

- [x] Persist logged user information inside session or cookie (user login information and token)
- [x] Check if the user logged information will not be lost inside components
- [x] Update Permissions methods using the new approach.

## Analysis

Based on the context using `next.js` and `next-auth`, when the user logs in on Github or any other social media, the user information used to be stored on a `session` [state]( https://next-auth.js.org/tutorials/securing-pages-and-api-routes). 

The issue is when `gift-publisher` uploads a file to a `gift`portal` API route,  they do not share th same `session`.

The user information must persist to be accessed inside any route or app inside the same domain.

The cookie cannot be set inside any callback from the `login` workflow, I made some tests and it must be done after login.

Inside user logs in it is going to be set as a `cookie`, and will be removed from the `session` described before`.

**Comment by cotts** [comment]
This issue toke more than expected related to the points below:

- User access tokens weren't working correctly on GIthub API, and some tests were made and some fixes are done.
- To persist user information, some tests were made to validate the best place to include the persistent user information.
- Check how to secure the stored information.
