### ISSUE TITLE
Default branch of all `gift-data` and `os-data` repositories should be set to `main`

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#70]
When I retrieve repository information on GitHub to manage the state of the Portal, I want to make sure that the default branch is set to `main` so I can optimize the code in this repository and avoid unnecessary checks due to legacy branches still set to be using the `master` branch.

* Unblocks #61 (blocker detailed in [this comment](https://github.com/datopian/gift-portal/issues/61#issuecomment-764792071)).

## Acceptance

* [ ] All repositories at https://github.com/gift-data/ have their default branch set to `main`.
* [ ] All repositories at https://github.com/os-data/ have their default branch set to `main`.

## Tasks

* [ ] Create a script that loops over all the repositories in a given organization and sets the `default_branch` property to `main`.
  * [ ] Have a valid access token.
  * [ ] Read the response code from each request to make sure we get back `200` for all of the repos.

## Analysis

* This should be done in batch (looping over all repositories) with the GitHub API in a way similar to this answer https://stackoverflow.com/a/55698028/8787680
* The relevant documentation on GitHub can be found here https://docs.github.com/en/rest/reference/repos#update-a-repository

**Comment by sglavoie** [comment]
FIXED: All tasks done. See script below.

```
// First we need to do
// npm install @octokit/core

const { Octokit } = require("@octokit/core");

const octokit = new Octokit({ auth: `some_personal_token` });

// const owner = "gift-data";
const owner = "os-data";

// GIFT
// repos = [
//   "south-africa-national-estimates-2015-2019",
//   "republica-dominicana-gastos-economica-2014-2020",
//  ...
// ]

// OpenSpending
repos = [
  "wesel",
  // "washington-dc-employee-salaries",
  // "ukraine-transactions-sep-11-2015-sep-15-2015",
  // ...
];

async function getSha(repo) {
  const response = await octokit.request(
    `GET /repos/${owner}/${repo}/commits/master`
  );
  const sha1 = response.data.sha;
  return sha1;
}

async function createMainBranch(repo) {
  const sha1 = await getSha(repo);
  await octokit.request(`POST /repos/${owner}/${repo}/git/refs`, {
    ref: "refs/heads/main",
    sha: sha1,
  });
}

async function setDefaultBranchToMain(repo) {
  await createMainBranch(repo);
  await octokit.request(`PATCH /repos/${owner}/${repo}`, {
    owner: owner,
    repo: repo,
    name: repo,
    default_branch: "main",
  });
}

// Don't make too many requests too quickly, else we will get blocked ;)...
for (const repo of repos) {
  setDefaultBranchToMain(repo);
}
```
