### ISSUE TITLE
Introducing apollo for state management and using it to power the MetaStore

### ISSUE THREAD

**Issue by risenW** [datopian/gift-portal#75]
We want a seamless way of dealing with the cache and global states in Gift-portal. We want to be able to retrieve cached data easily as well as update datasets that are out of date.

## Acceptance

* [x] There is a MetaStore class with the following API **Done** https://github.com/datopian/gift-portal/blob/master/lib/Metastore.js
  * [x] MetaStore.fetch()  **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/lib/Metastore.js#L38
  * [x] MetaStore.create **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/lib/Metastore.js#L54
  * [x] MetaStore.update **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/lib/Metastore.js#L78
  * [x] MetaStore.search('') => for now this can return "all" datasets if no query string **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/lib/Metastore.js#L21
  * [ ] Future: MetaStore.delete
* [x] I have set up apollo for local state management **Done** https://github.com/datopian/gift-portal/blob/master/lib/apolloClient.js
* [x] MetaStore uses apollo as proxy for queries and for caching  **Done* https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/lib/Metastore.js#L18
* [x] On app boot, I pre-populate the store based on all datasets in a github org **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/pages/index.js#L60

## Task

* [x] Introduce apollo for local state management
* [x] Wire up MetaStore to use apollo local state
* [x] Refactor app boot code that loads metastore to ...
  * [x] Use metastore-lib-js
  * [x] Store this in apollo
  * [x] Wire up apollo local store to use metastore-lib-js to do the action
  * [x] fetch: retrieve if it doesn't have the value already

### Analysis

See detailed analysis and why we recommended using Apollo in this issue #72 

### More Analysis

* Dataset fetched from github + datapackage.json via MetaStore.fetch
* Two options
  * `datapackage.json` exists in github => use that as descriptor
    * Add githubId if not present when we do the fetch (FUTURE: maybe we can assume this is always there ...)
  * does not exist => create a minimal descriptor with name and githubId and empty resources array

What does a Dataset descriptor look like for these datasets

```
{
  // minimum info
  name: "presepuseto-mexico",
  id: "github repo id"  // (unique i hope?) Thadeu: node id
  
  // much more ... 
}
```

// on app boot we still pre-load the "state" cache like we do currently but put it
// into apollo ...
```
MetaStore.fetch
  => look in apollo ...
  => apollo will return if already has it ...
  => o/w apollo will use metastore-lib-js to load and then return
```

**Comment by rufuspollock** [comment]
Two small items:

1. ```MetastoreApollo => MetaStore```
2. Please put comments here about why you adopted caching strategy you did vs just having apollo run the cache

**Comment by risenW** [comment]
> Two small items:
> 
> 1. `MetastoreApollo => MetaStore`
> 2. Please put comments here about why you adopted caching strategy you did vs just having apollo run the cache (and why different from e.g. https://github.com/datopian/portal.js/blob/master/packages/portal/lib/apolloClient.ts#L4)

1 Fixed in https://github.com/datopian/gift-portal/pull/92
2. I did more research and found a similar way to use the Apollo similar to what we have in portal.js. I have refactored https://github.com/datopian/gift-portal/pull/85  to use these findings. Find new pull request https://github.com/datopian/gift-portal/pull/95

I referenced this blog: https://www.apollographql.com/blog/building-a-next-js-app-with-apollo-client-slash-graphql/

**Comment by sglavoie** [comment]
FIXED: All tasks done.

Will still need to do this:

* Future: MetaStore.delete
