### ISSUE TITLE
Updating Publisher flow to support editing and adding data to existing dataset

### ISSUE THREAD

**Issue by steveoni** [datopian/gift-portal#78]
we want to enable editing and adding data to an existing dataset.

## Acceptance

* [ ] create another view to use on edit mode
* [ ] check permission to edit/write on this dataset
* [ ] when dataset is clicked; direct user to dataset `edit` page if it contains existing `datapackage.json` and if does not redirect to create new data.
* [ ] if the user has permissions, the `datapackage.json` can be retrived using the function `_getDatasetMetdata` on https://github.com/datopian/gift-portal/blob/master/lib/Download.js#L115

## Task

* [ ] add dataset edit page to `gift-portal`
* [ ] check permssion on dataset edit page
* [ ] obtain dataset datapackage.json and pass down to `gift-publisher` as props
* [ ] dataset datapackage.json is updated base on operation in publisher
* [ ] `Metastorlib` update function is used to update the existing datapackge.json with the new datapackage.json
