### ISSUE TITLE
Refactor Publisher App and info passed to take a dataset

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#79]
Explicitly boot app with a dataset object `{...}` and set the resource object if dataset has a resource ...

## Acceptance

* [x] Publisher app has a `DatasetEditor` rather than `ResourceEditor`. **DONE** -https://github.com/datopian/gift-publisher/blob/package/src/App.js
* [x] Publisher app flow should work with an existing dataset with existing data file (i.e. i can boot in and go through flow).
  * [x] Add a "Next" button on the "Add data" screen so i can skip this screen if already have data. **DONE** - https://github.com/datopian/gift-publisher/blob/510ab3d5c5e69f65efd1f36785a4cbebbb0f011e/src/App.js#L354
* [x] Publisher app 404s if no dataset with the id passed to the admin app **DONE** - https://github.com/datopian/gift-portal/blob/a06b78334c0aa2fb22d79390651338c4d78cc632/pages/admin/publisher/%5Bid%5D.js#L25

## Tasks

* [x] Refactor https://github.com/datopian/gift-portal/blob/master/pages/admin/publisher/%5Bid%5D.js to get a dataset and pass it over (see analysis below) **DONE** - https://github.com/datopian/gift-portal/blob/refactor/pages/admin/publisher/%5Bid%5D.js#L25
  * [x] (404 fix) look up that dataset from the MetaStore and If not there: return 404 **DONE**
* [x] Refactor publisher app to receive dataset object and use it appropriately https://github.com/datopian/gift-publisher/blob/main/src/App.js
  * [x] Rename ResourceEditor => DatasetEditor **DONE** - https://github.com/datopian/gift-publisher/blob/bac93a18637dedc28b2131489d64e3c1e0085151/src/App.js#L17
  * [x] Change props as described (see analysis below)
    * [x] dataset is primary item now
    * [x] authorizeApi
    * [x] metastoreApi 
  * [x] Add Next button on "Provide your data" **DONE** - https://github.com/datopian/gift-publisher/blob/bac93a18637dedc28b2131489d64e3c1e0085151/src/App.js#L438
    * [x] Enable if dataset resources array has at least one item (disable otherwise)

### Gift portal admin/publisher/[id] page

```javascript=
import { DatasetEditor } from 'giftpub'

export default function Publisher({ lfsServerUrl, dataset }) {

  const config = {
    dataset: dataset,
    lfs: lfsServerUrl,
    authorizeApi: /api/authorize/
    metastoreApi: /api/dataset/
  }
  // eslint-disable-next-line react/react-in-jsx-scope
  return <DatasetEditor config={config} />
}

Publisher.getInitialProps = async (ctx) => {
  dataset = MetaStore.fetch(ctx.query.id)

  return {
    lfsServerUrl: process.env.GIFTLESS_SERVER,
    // dataset should be Frictionless Data descriptor
    // may be e.g dataset.descriptor if dataset from
    // metastore is "richer" than simple descriptor
    dataset: dataset,
  }
}
```

### Gift Publisher refactor

```javascript=
export class ResourceEditor extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      datasetId: this.props.config.datasetId,
      resourceId: "",
      resource: this.props.resource || {},
      ...
      
// Change to 👇

export class DatasetEditor extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      dataset: this.props.dataset,
      // danger of this what happens if in the App we then remove
      // the only resource and upload a new file
      // resource will now be holding the metadata of the old file
      // that we removed
      // MINOR: for now we can go with this approach and refactor
      // later if needed
      resource: this.props.dataset.resources[0] || {},
      ...


// Step 1: upload

// get the authorize token for accessing giftless
// this step is skipped atm as no authorization on giftless - but one day ...
DatasetEditor.props.datasetApi + ?... dataset.id ...


// Step 4:

// /api/dataset/{name/id}
DatasetEditor.props.datasetApi + dataset.name
```

**Comment by steveoni** [comment]
@rufuspollock we did not specify the passing of `datasetId` to the `DatasetEditor`, currently, the `giftless-client.js` will need this `datasetId` in the `upload` method.

And currently, the `datapackage` does not have an id that can be accessed via `dataset.id`

**Comment by sglavoie** [comment]
FIXED: All tasks done :tada:.

* Publisher app has a `DatasetEditor` rather than `ResourceEditor`. **DONE** -https://github.com/datopian/gift-publisher/blob/package/src/App.js
* Publisher app flow should work with an existing dataset with existing data file (i.e. i can boot in and go through flow).
  Add a "Next" button on the "Add data" screen so i can skip this screen if already have data. **DONE** - https://github.com/datopian/gift-publisher/blob/510ab3d5c5e69f65efd1f36785a4cbebbb0f011e/src/App.js#L354
* Publisher app 404s if no dataset with the id passed to the admin app **DONE** - https://github.com/datopian/gift-portal/blob/a06b78334c0aa2fb22d79390651338c4d78cc632/pages/admin/publisher/%5Bid%5D.js#L25
