### ISSUE TITLE
Refactor pages to use new Apollo based Metastore

### ISSUE THREAD

**Issue by risenW** [datopian/gift-portal#88]
All pages are using the new apollo metastore created in #75 

## Acceptance
* [x] Index/home page loads data using metastoreApollo **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/pages/index.js#L67
* [x] dataset page loads data using metastoreApollo  **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/pages/dataset/%5Bdatasetid%5D.js#L232
* [x] dashboard page loads data using metastoreApollo **Done** https://github.com/datopian/gift-portal/blob/26029e86f70cb23ba802bddcf3219a17867149e6/pages/dashboard.js#L39

## Tasks
* [x] Refactor Index/home page to load data using metastoreApollo search method
* [x] Refactor dataset page to load data using metastoreApollo fetch method
* [x] Refactor dashboard page to load data using metastoreApollo
