### ISSUE TITLE
Dataset page fully working

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#9]
When I visit a dataset page, I want to see relevant information being rendered so I can know we are on the right track to displaying the correct data with a preview of said data.

## Acceptance

* [ ] The dataset page is fully working. Accessing it renders the necessary information for a given dataset.

## Tasks

* [x] Add some fixture data (as CSV) in fixtures directory (e.g. `paraguay` directory with `datapackage.json` inside with `README.md` → Add the README) for the datasets we have (not full files for now, 10-50 kb/file) [**@sglavoie**] – **DONE**: Datasets added in 559047876a12061938ce064776e652ad17fc5e4b. They're found at https://github.com/datopian/gift-portal/tree/master/fixtures.
* [x] Load that data and README into `db.catalog`
  * [x] Add a readme attribute to data
  * [x] and add as `sample` attribute on resource (parse CSV into JSON)
* [x] Stub layout based on mockup (other than preview table)
  * [x] Render README as markdown with sample at top and more info at bottom like we do on DataHub.io
    * [x] We might want to extract the readme renderer we have on DataHub and reuse (one day this can end up in Portal.js common lib)
* [x] Data preview in table using `sample` data (? reuse table renderer work from graphql data explorer?)
  * [x] Ask Anu or similar what React component to use for the table
  * [x] Use it!
