### ISSUE TITLE
Update Permissions using Apollo

### ISSUE THREAD

**Issue by cotts** [datopian/gift-portal#90]
Today the user permissions are checked using a file stored locally after the app boots and it must be changed to be stored on the Apollo cache.

## Acceptance Criteria
- [x] Update permissions using Apollo instead of local file
- [x] Remove local file generate when the app boots

## Tasks
- [x] Update generate permissions from Github using Apollo
- [x] Add Tests
- [x] Update tests with new scope
- [x] Update API routes to get permission from Apollo
- [x] Remove unused methods

**Comment by rufuspollock** [comment]
@risenW @cotts i think this makes sense but i'd like to understand a bit more. why do we need this? (I imagine use case is when someone has created a new repo ... or has added a user to a repo ...). this seem useful but marginal use cases atm so this wouldn't be on the critical path ...

**Comment by cotts** [comment]
> @risenW @cotts i think this makes sense but i'd like to understand a bit more. why do we need this? (I imagine use case is when someone has created a new repo ... or has added a user to a repo ...). this seem useful but marginal use cases atm so this wouldn't be on the critical path ...

@rufuspollock That was supposed to replace the data file to check the permissions and as you said, can be updated from time to time or using some trigger/webhook to avoid permissions be outdated. 

I can leave It to be done later, I just need to know the critical path to keep working.
