### ISSUE TITLE
[epic] Updating Publisher flow to support editing (and adding data) to existing dataset

### ISSUE THREAD

**Issue by sglavoie** [datopian/gift-portal#91]
When I want to correct or adjust some metadata in an existing dataset I want a UI to edit that information so that I have updated dataset metadata

When I have an existing dataset I want to add/remove data files including have more than one data file (but same schema) so that ...

## Flows

* Create (no data yet): one file, one schema
  * Dataset with no resources
  * Load a file
  * Infer schema
  * Edit schema
  * Add dataset level metadata
* Create 2: multiple files, one schema (?? do not support for now?)
* Edit (already data and a schema) **Assumption: only one common schema for all files ...**
  * No change in data: just edit metadata
    * => skip data screen at start ...
  * Remove data file and add data: => merge schema (if merge fails just start again from infer) and then edit
    * => Or we just dump the schema and people have to re-enter ...
  * Add data (and keep existing data) => use existing schema (what to do if conflict? e.g. 2nd file does not match existing schema)
  * (Just) Remove data: sort of easy ...

Figma: https://www.figma.com/file/TX849YGwnoq5l8387x5DTj/GIFT---Publishing-Flow?node-id=0%3A1
Google Drawing: https://docs.google.com/drawings/d/12iliJXWQDEnH3AP21iDxW9L4jDrK4kBALk7oZYksiZA/edit

```mermaid
graph LR

subgraph "One file, one schema"
  fileB1 --> schemaB1
end

subgraph "Multiple files, one shared schema"
  fileC1 --> schemaC1
  fileC2 --> schemaC1
end

subgraph "Multiple files, separate schemas"
  fileA1 --> schemaA1
  fileA2 --> schemaA2
end
```

## Acceptance

* [x] In an appropriate location e.g. dashboard there is an option to edit the datasets that I have edit access to **DONE**: There is a link `Edit fiscal data schema` in the dashboard to do that for datasets the user has access to.
* [x] There is a UI for editing an existing dataset **DONE**: There is a link `Edit fiscal data schema` in the dashboard to do that for datasets the user has access to and this is a very similar flow to the "create flow" one.
* [x] There is a UI for adding and removing the data files **DONE**: See the video below.
  * [x] It is available in the create flow when accessed from the portal. (Confirm it's integrated.)
  * [x] It is available in the edit flow when accessed from the portal. (Confirm it's integrated.)

## Task

* [x] Refactor publisher app and info passed to it from `gift-portal` #79 **DONE**: [See this comment for details](https://github.com/datopian/gift-portal/issues/79#issuecomment-771633926).
* [x] Rework Screen 1 "Provide Your Data" to support multiple files: adding and removing files and displaying files https://github.com/datopian/gift-publisher/issues/36 **DONE**: See the video below.
* [x] Rework screen 2 **DONE**: Done with https://github.com/datopian/gift-publisher/issues/36, see video below.
* [x] Update metadata fields in datapackage.json on edit Metadata workflow.

https://user-images.githubusercontent.com/29900845/107044312-6757f280-67c4-11eb-93d1-bc2b9a7dffcd.mov

**Comment by sglavoie** [comment]
FIXED: All tasks were done. The integration of those features can be tested from the dashboard when logged in (must have access to https://github.com/gift-data/ organization): https://gift-portal-git-master.datopian1.vercel.app/

[See video in the description above](https://github.com/datopian/gift-portal/issues/91#issue-798439988) for a visual tour.
