### ISSUE TITLE
Fix Login/Logout Redirect

### ISSUE THREAD

**Issue by cotts** [datopian/gift-portal#93]
When the user login/logout, I want to be redirected to the right place for each action.

* **Problem**: The redirects don't work reliably. If the user logs in, a redirect to `/dashboard` should occur. When logging out, a redirect to `/` should occur.
* **Bug description**: If the user logs in then logs out and does that more than once, a redirect to `/` will occur when logging in instead of showing `/dashboard`.
* **How do we know this bug has been solved?** → The user can log in and log out repeatedly and sees the correct routes: when logging in, the route `/dashboard` is always shown; when logging out, the route `/` is always shown.

## Acceptance Criteria
- [ ] When the user logs in, it should redirect to the '/dashboard' page
- [ ] When the user logs out, it should redirect to the '/' page and clean the `cookie` and user `session` 

## Tasks

- [ ] Create a logout component
- [ ] Ask if the user really wants to logout: `Logout` or `Go Back`
- [ ] Handle the session when the user logout (clean user `cookie` and `session`)
- [ ] Redirect to the main page if the user logs out
- [ ] Update `redirect` callback on `nextauth` API Route

## Analysis

To handle the redirect when the user logs in or out inside the app, the `next-auth` redirect callback option is limited to receive the `url` and `baseUrl` as parameters.

Some tests were made to validate the user session and there was no success to check if the user session or cookie and redirect to the right place based on each action.

In this case, is necessary to create a component to handle the user logout.

**Comment by sglavoie** [comment]
Issue updated with a description of the bug. Moving this issue to **Someday Maybe** because we have other things to focus on: we can live with this one for now.

**Comment by sglavoie** [comment]
WONTFIX: PR #158 took care of this issue with a different approach, so this one is no longer relevant.
