### ISSUE TITLE
Add Cypress Tests

### ISSUE THREAD

**Issue by cotts** [datopian/gift-portal#94]
Add Cypress on Components

## Acceptance Criteria

- [x] Have all Routes tested
- [x] Have Workflow tested
- [x] Validate component fields and values
- [x] Add on the documentation how to make tests

## Tasks

- [x] Add mocked objects and routes responses
  - [x] authenticated user
  - [x] datasets response
  - [x] one dataset in `Edit discal data schema` mode
  - [x] one `Create a fiscal data schema` mode
- [x] Add pages tests scenarios
  - [x] An logged user dashboard navigation
  - [x] An annonymous user dashboard navigation
  - [x] A logged user going to `Create a Fiscal data schema`
  - [x] A logged user going to `Edit fiscal data schema`
- [x] Update documentation
- [x] Update Environment keys
  - [x] Locally  
  - [x] Github repo settings
  - [x] Vercel repo settings

## Analysis

To be able to run the tests using best practices and avoid using real data, there was some tricky issues that required some time until I got the solutions.

_Problems found_: 

- To mock authenticated user **DONE**
  To be able to mock the user, after trying the main documentation from `next-auth` and some posts for a while, the way that worked in this scenario was fake a call to the API route `/api/auth/session` with the user that I will use on the tests.
 E.g.:

```
   cy.intercept({
      method: 'GET',
      url: '/api/auth/session'
    }, {
      "user":{
        "name":"John Doe",
        "email":"johndoe@email.com",
        "image":"https://avatars.githubusercontent.com/u/1112221?v=4"
      },
      "expires":"2021-03-05T13:47:17.273Z",
      "userInfo":"eyJhbGciOiJIUzI1NiJ9.eyJsb2dpbiI6ImpvaG5kb2UiLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5kb2VAZW1haWwuY29tIiwidG9rZW4iOnsicHJvdmlkZXIiOiJnaXRodWIiLCJ0eXBlIjoib2F1dGgiLCJpZCI6MjIyMzQsImFjY2Vzc1Rva2VuIjoiMDRiYTZmYWMyZWMyMjIyMmRlY2EyMjI4MTM0NDQ0ZTY2NjY4OWJhOWIxIiwiYWNjZXNzVG9rZW5FeHBpcmVzIjpudWxsfX0.sLqSe-nP0suYKcAI_JcZJkSoVS9megeW-n9uc08mGdU"
    })
```

- Mock the main datasets request  **DONE** 
  
  To mock the initial datasets information, the app make a request on an `Apollo` request in the server side using the `getServerSideProps`.
In this case, the method above to intercept the request and mock data will not work.   
After make some research about how that can be done, I got the strategy to `Mock Service Worker` and I will continue on this to be able to run all the workflow without the need to use real data.
Ref about strategy that I will use: https://github.com/vercel/next.js/tree/canary/examples/with-msw

**Comment by cotts** [comment]
All tests created are working ok locally but the Cypress workflow on GIthub Actions aren't 
I'm investigating how to solve this issue.
